server:
  port: 7001

eureka:
  instance:
    #hostname: localhost
    hostname: eureka7001.com
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: false
    #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务。
    #如果自己不是注册中心的话，又需要去检索服务的话，应当设置为true
    fetch-registry: false
    service-url:
      # 单机版 自己注册自己  多服务器版 自己注册到除开自己以外的所有
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      # 设置与eureka server交互的地址查询服务和注册服务器都需要依赖这个地址。
      #defaultZone: http://eureka7002.com:7002/eureka
